# .cargo/config.toml

[target.aarch64-linux-android]

linker = "aarch64-linux-android-clang"
ar = "aarch64-linux-android-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi-clang"
ar = "arm-linux-androideabi-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android-clang"
ar = "x86_64-linux-android-ar"