# 为 aarch64 (ARM64) 安卓目标指定链接器
[target.aarch64-linux-android]

linker = "aarch64-linux-android21-clang"
ar = "aarch64-linux-android-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
ar = "arm-linux-androideabi-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "x86_64-linux-android-ar"